CREATE TABLE
  IF NOT EXISTS Customer (
    Phone_number VC NOT NULL,
    Email VC NOT NULL,
    First_name VC NOT NULL,
    Last_name VC NOT NULL,
    Gender VC,
    Registration_date DATE NOT NULL,
    Password_hashed VC NOT NULL,
    Date_of_birth DATE NOT NULL,
    Country VC NOT NULL,
    State VC NOT NULL,
    City VC NOT NULL,
    Street VC NOT NULL,
    Building INT NOT NULL,
    Apartment INT NOT NULL,
    CONSTRAINT PK_Customer PRIMARY KEY (Phone_number),
    CONSTRAINT Customer_CK_Gender CHECK (Gender IN ('Male', 'Female')),
    CONSTRAINT Customer_CK_Email CHECK (Email LIKE '%@%.%'),
    CONSTRAINT Customer_CK_Password CHECK (LENGTH (Password_hashed) >= 8),
    CONSTRAINT Customer_CK_Date_of_birth CHECK (Date_of_birth < CURRENT_DATE),
    CONSTRAINT Customer_CK_Registration_date CHECK (Registration_date < CURRENT_DATE),
    CONSTRAINT Customer_CK_Apartment CHECK (Apartment >= 0),
    CONSTRAINT Customer_CK_Building CHECK (Building >= 0),
    CONSTRAINT Customer_UK_Email UNIQUE (Email),
    CONSTRAINT Customer_UK_Phone_number UNIQUE (Phone_number),
    CONSTRAINT Customer_UK_LOCATION UNIQUE (Country, State, City, Street, Building, Apartment)
  );