CREATE TABLE
  IF NOT EXISTS Employee (
    SSN VC NOT NULL,
    Position VC NOT NULL,
    Salary INT NOT NULL,
    Hire_date DATE NOT NULL,
    Gender VARCHAR(6) NOT NULL,
    Date_of_birth DATE NOT NULL,
    Email VC NOT NULL,
    First_name VC NOT NULL,
    Last_name VC NOT NULL,
    Phone_number PHONE_NUMBER NOT NULL,
    Country VC NOT NULL,
    State VC NOT NULL,
    City VC NOT NULL,
    Street VC NOT NULL,
    Building INT NOT NULL,
    Apartment INT NOT NULL,
    Branch_phone_number PHONE_NUMBER,
    Supervisor_SSN VC,
    Department_name VC NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (SSN),
    CONSTRAINT Employee_FK_Branch_phone_number FOREIGN KEY (Branch_phone_number) REFERENCES Branch (Phone_number) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT Employee_FK_Supervisor_SSN FOREIGN KEY (Supervisor_SSN) REFERENCES Employee (SSN) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT Employee_FK_Department_name FOREIGN KEY (Department_name) REFERENCES Department (Name) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT Employee_CK_Gender CHECK (Gender IN ('Male', 'Female')),
    CONSTRAINT Employee_CK_Date_of_birth CHECK (Date_of_birth < CURRENT_DATE),
    CONSTRAINT Employee_CK_Salary CHECK (Salary > 0),
    CONSTRAINT Employee_CK_Apartment CHECK (Apartment >= 0),
    CONSTRAINT Employee_CK_Building CHECK (Building >= 0),
    CONSTRAINT Employee_CK_Hire_date CHECK (Hire_date < CURRENT_DATE),
    CONSTRAINT Employee_CK_Email CHECK (Email LIKE '%@%.%'),
    CONSTRAINT Employee_CK_Position CHECK (
      Position IN ('Manager', 'MarketingHead', 'HRManager', 'FinanceManager', 'OperationsHead', 'ITSpecialist', 'SupportManager', 'LogisticsHead', 'LegalAdvisor', 'R&DManager', 'Trainer', 'ProcurementOfficer', 'AdminAssistant', 'FacilitiesManager', 'ComplianceOfficer', 'Driver')
    ),
    CONSTRAINT Employee_UK_Phone_number UNIQUE (Phone_number),
    CONSTRAINT Employee_UK_Email UNIQUE (Email),
    CONSTRAINT Employee_UK_SSN UNIQUE (SSN),
    CONSTRAINT Employee_UK_LOCATION UNIQUE (Country, State, City, Street, Building, Apartment)
  );